# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/forms/dienstnehmerDetailForm.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DienstnehmerDetailForm(object):
    def setupUi(self, DienstnehmerDetailForm):
        DienstnehmerDetailForm.setObjectName(_fromUtf8("DienstnehmerDetailForm"))
        DienstnehmerDetailForm.resize(687, 802)
        self.gridLayout = QtGui.QGridLayout(DienstnehmerDetailForm)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_dienstnehmer = QtGui.QGroupBox(DienstnehmerDetailForm)
        self.groupBox_dienstnehmer.setObjectName(_fromUtf8("groupBox_dienstnehmer"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_dienstnehmer)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.groupBox_dienstnehmer)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_nummer = QtGui.QLineEdit(self.groupBox_dienstnehmer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nummer.sizePolicy().hasHeightForWidth())
        self.lineEdit_nummer.setSizePolicy(sizePolicy)
        self.lineEdit_nummer.setObjectName(_fromUtf8("lineEdit_nummer"))
        self.horizontalLayout_5.addWidget(self.lineEdit_nummer)
        self.label_4 = QtGui.QLabel(self.groupBox_dienstnehmer)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_svnr = QtGui.QLineEdit(self.groupBox_dienstnehmer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_svnr.sizePolicy().hasHeightForWidth())
        self.lineEdit_svnr.setSizePolicy(sizePolicy)
        self.lineEdit_svnr.setObjectName(_fromUtf8("lineEdit_svnr"))
        self.horizontalLayout_5.addWidget(self.lineEdit_svnr)
        self.pushButton_color = QtGui.QPushButton(self.groupBox_dienstnehmer)
        self.pushButton_color.setObjectName(_fromUtf8("pushButton_color"))
        self.horizontalLayout_5.addWidget(self.pushButton_color)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.groupBox_dienstnehmer)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_nachname = QtGui.QLineEdit(self.groupBox_dienstnehmer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nachname.sizePolicy().hasHeightForWidth())
        self.lineEdit_nachname.setSizePolicy(sizePolicy)
        self.lineEdit_nachname.setObjectName(_fromUtf8("lineEdit_nachname"))
        self.horizontalLayout_4.addWidget(self.lineEdit_nachname)
        self.label_2 = QtGui.QLabel(self.groupBox_dienstnehmer)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_vorname = QtGui.QLineEdit(self.groupBox_dienstnehmer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vorname.sizePolicy().hasHeightForWidth())
        self.lineEdit_vorname.setSizePolicy(sizePolicy)
        self.lineEdit_vorname.setObjectName(_fromUtf8("lineEdit_vorname"))
        self.horizontalLayout_4.addWidget(self.lineEdit_vorname)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.groupBox_dienstnehmer)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.doubleSpinBox_maxLohn = QtGui.QDoubleSpinBox(self.groupBox_dienstnehmer)
        self.doubleSpinBox_maxLohn.setMaximum(99999.99)
        self.doubleSpinBox_maxLohn.setObjectName(_fromUtf8("doubleSpinBox_maxLohn"))
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_maxLohn)
        self.label_6 = QtGui.QLabel(self.groupBox_dienstnehmer)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.comboBox_bereich = QtGui.QComboBox(self.groupBox_dienstnehmer)
        self.comboBox_bereich.setObjectName(_fromUtf8("comboBox_bereich"))
        self.horizontalLayout_8.addWidget(self.comboBox_bereich)
        self.label_7 = QtGui.QLabel(self.groupBox_dienstnehmer)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.comboBox_gehalt = QtGui.QComboBox(self.groupBox_dienstnehmer)
        self.comboBox_gehalt.setObjectName(_fromUtf8("comboBox_gehalt"))
        self.horizontalLayout_8.addWidget(self.comboBox_gehalt)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_dienstnehmer, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(DienstnehmerDetailForm)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_newEreignis = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_newEreignis.setObjectName(_fromUtf8("pushButton_newEreignis"))
        self.horizontalLayout.addWidget(self.pushButton_newEreignis)
        self.pushButton_deleteEreignis = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_deleteEreignis.setObjectName(_fromUtf8("pushButton_deleteEreignis"))
        self.horizontalLayout.addWidget(self.pushButton_deleteEreignis)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView_ereignisse = QtGui.QTableView(self.groupBox_2)
        self.tableView_ereignisse.setObjectName(_fromUtf8("tableView_ereignisse"))
        self.verticalLayout.addWidget(self.tableView_ereignisse)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(DienstnehmerDetailForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.label_3.setBuddy(self.lineEdit_nummer)
        self.label_4.setBuddy(self.lineEdit_svnr)
        self.label.setBuddy(self.lineEdit_nachname)
        self.label_2.setBuddy(self.lineEdit_vorname)
        self.label_5.setBuddy(self.doubleSpinBox_maxLohn)
        self.label_6.setBuddy(self.comboBox_bereich)
        self.label_7.setBuddy(self.comboBox_gehalt)

        self.retranslateUi(DienstnehmerDetailForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DienstnehmerDetailForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DienstnehmerDetailForm.reject)
        QtCore.QMetaObject.connectSlotsByName(DienstnehmerDetailForm)
        DienstnehmerDetailForm.setTabOrder(self.lineEdit_nummer, self.lineEdit_svnr)
        DienstnehmerDetailForm.setTabOrder(self.lineEdit_svnr, self.pushButton_color)
        DienstnehmerDetailForm.setTabOrder(self.pushButton_color, self.lineEdit_nachname)
        DienstnehmerDetailForm.setTabOrder(self.lineEdit_nachname, self.lineEdit_vorname)
        DienstnehmerDetailForm.setTabOrder(self.lineEdit_vorname, self.doubleSpinBox_maxLohn)
        DienstnehmerDetailForm.setTabOrder(self.doubleSpinBox_maxLohn, self.comboBox_bereich)
        DienstnehmerDetailForm.setTabOrder(self.comboBox_bereich, self.comboBox_gehalt)
        DienstnehmerDetailForm.setTabOrder(self.comboBox_gehalt, self.pushButton_newEreignis)
        DienstnehmerDetailForm.setTabOrder(self.pushButton_newEreignis, self.pushButton_deleteEreignis)
        DienstnehmerDetailForm.setTabOrder(self.pushButton_deleteEreignis, self.buttonBox)
        DienstnehmerDetailForm.setTabOrder(self.buttonBox, self.tableView_ereignisse)

    def retranslateUi(self, DienstnehmerDetailForm):
        DienstnehmerDetailForm.setWindowTitle(_translate("DienstnehmerDetailForm", "Dienstehmer Details", None))
        self.groupBox_dienstnehmer.setTitle(_translate("DienstnehmerDetailForm", "Dienstnehmer", None))
        self.label_3.setText(_translate("DienstnehmerDetailForm", "Numme&r", None))
        self.label_4.setText(_translate("DienstnehmerDetailForm", "&SVNr.", None))
        self.pushButton_color.setText(_translate("DienstnehmerDetailForm", "&Farbe", None))
        self.label.setText(_translate("DienstnehmerDetailForm", "&Nachname", None))
        self.label_2.setText(_translate("DienstnehmerDetailForm", "&Vorname", None))
        self.label_5.setText(_translate("DienstnehmerDetailForm", "Max. &Lohn", None))
        self.label_6.setText(_translate("DienstnehmerDetailForm", "&Bereich", None))
        self.label_7.setText(_translate("DienstnehmerDetailForm", "&Gehalt", None))
        self.groupBox_2.setTitle(_translate("DienstnehmerDetailForm", "Ereignisse", None))
        self.pushButton_newEreignis.setText(_translate("DienstnehmerDetailForm", "&Hinzufügen", None))
        self.pushButton_deleteEreignis.setText(_translate("DienstnehmerDetailForm", "&Löschen", None))

import lagerManager_rc
