# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/forms/lieferungDetailForm.ui'
#
# Created: Tue Mar 12 20:01:58 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LieferungDetailForm(object):
    def setupUi(self, LieferungDetailForm):
        LieferungDetailForm.setObjectName(_fromUtf8("LieferungDetailForm"))
        LieferungDetailForm.resize(687, 693)
        self.gridLayout = QtGui.QGridLayout(LieferungDetailForm)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_lieferung = QtGui.QGroupBox(LieferungDetailForm)
        self.groupBox_lieferung.setObjectName(_fromUtf8("groupBox_lieferung"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_lieferung)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox_lieferung)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit_id = QtGui.QLineEdit(self.groupBox_lieferung)
        self.lineEdit_id.setReadOnly(True)
        self.lineEdit_id.setObjectName(_fromUtf8("lineEdit_id"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_id)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.plainTextEdit_comment = QtGui.QPlainTextEdit(self.groupBox_lieferung)
        self.plainTextEdit_comment.setObjectName(_fromUtf8("plainTextEdit_comment"))
        self.horizontalLayout_4.addWidget(self.plainTextEdit_comment)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_4 = QtGui.QLabel(self.groupBox_lieferung)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit_dokId = QtGui.QLineEdit(self.groupBox_lieferung)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dokId.sizePolicy().hasHeightForWidth())
        self.lineEdit_dokId.setSizePolicy(sizePolicy)
        self.lineEdit_dokId.setReadOnly(True)
        self.lineEdit_dokId.setObjectName(_fromUtf8("lineEdit_dokId"))
        self.horizontalLayout_2.addWidget(self.lineEdit_dokId)
        self.pushButton_fileChooser = QtGui.QPushButton(self.groupBox_lieferung)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_fileChooser.sizePolicy().hasHeightForWidth())
        self.pushButton_fileChooser.setSizePolicy(sizePolicy)
        self.pushButton_fileChooser.setObjectName(_fromUtf8("pushButton_fileChooser"))
        self.horizontalLayout_2.addWidget(self.pushButton_fileChooser)
        self.label_document = ClickableLabel(self.groupBox_lieferung)
        self.label_document.setText(_fromUtf8(""))
        self.label_document.setObjectName(_fromUtf8("label_document"))
        self.horizontalLayout_2.addWidget(self.label_document)
        self.plainTextEdit_ocr = QtGui.QPlainTextEdit(self.groupBox_lieferung)
        self.plainTextEdit_ocr.setObjectName(_fromUtf8("plainTextEdit_ocr"))
        self.horizontalLayout_2.addWidget(self.plainTextEdit_ocr)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(7, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(self.groupBox_lieferung)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.comboBox_lieferant = QtGui.QComboBox(self.groupBox_lieferung)
        self.comboBox_lieferant.setObjectName(_fromUtf8("comboBox_lieferant"))
        self.horizontalLayout_5.addWidget(self.comboBox_lieferant)
        self.label_3 = QtGui.QLabel(self.groupBox_lieferung)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.dateEdit_datum = QtGui.QDateEdit(self.groupBox_lieferung)
        self.dateEdit_datum.setCalendarPopup(True)
        self.dateEdit_datum.setObjectName(_fromUtf8("dateEdit_datum"))
        self.horizontalLayout_5.addWidget(self.dateEdit_datum)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_lieferant = QtGui.QLabel(self.groupBox_lieferung)
        self.label_lieferant.setObjectName(_fromUtf8("label_lieferant"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_lieferant)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_lieferung, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(LieferungDetailForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(LieferungDetailForm)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_newDetail = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_newDetail.setObjectName(_fromUtf8("pushButton_newDetail"))
        self.horizontalLayout.addWidget(self.pushButton_newDetail)
        self.pushButton_deleteDetail = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_deleteDetail.setObjectName(_fromUtf8("pushButton_deleteDetail"))
        self.horizontalLayout.addWidget(self.pushButton_deleteDetail)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView_details = QtGui.QTableView(self.groupBox_2)
        self.tableView_details.setObjectName(_fromUtf8("tableView_details"))
        self.verticalLayout.addWidget(self.tableView_details)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 1)

        self.retranslateUi(LieferungDetailForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), LieferungDetailForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), LieferungDetailForm.reject)
        QtCore.QMetaObject.connectSlotsByName(LieferungDetailForm)

    def retranslateUi(self, LieferungDetailForm):
        LieferungDetailForm.setWindowTitle(QtGui.QApplication.translate("LieferungDetailForm", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_lieferung.setTitle(QtGui.QApplication.translate("LieferungDetailForm", "Lieferung", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LieferungDetailForm", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("LieferungDetailForm", "Dokument", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_fileChooser.setText(QtGui.QApplication.translate("LieferungDetailForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("LieferungDetailForm", "Kommentar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("LieferungDetailForm", "Datum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_lieferant.setText(QtGui.QApplication.translate("LieferungDetailForm", "Lieferant", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("LieferungDetailForm", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_newDetail.setText(QtGui.QApplication.translate("LieferungDetailForm", "&Hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_deleteDetail.setText(QtGui.QApplication.translate("LieferungDetailForm", "&Löschen", None, QtGui.QApplication.UnicodeUTF8))

from lib.ClickableLabel import ClickableLabel
import lagerManager_rc
