# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/lagerManagerMainWindow.ui'
#
# Created: Tue Oct  1 15:09:32 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1047, 664)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.horizontalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Reports = QtGui.QMenu(self.menubar)
        self.menu_Reports.setObjectName(_fromUtf8("menu_Reports"))
        self.menu_Einkauf = QtGui.QMenu(self.menu_Reports)
        self.menu_Einkauf.setObjectName(_fromUtf8("menu_Einkauf"))
        self.menu_Umsaetze = QtGui.QMenu(self.menu_Reports)
        self.menu_Umsaetze.setObjectName(_fromUtf8("menu_Umsaetze"))
        self.menu_Verbrauch = QtGui.QMenu(self.menu_Reports)
        self.menu_Verbrauch.setObjectName(_fromUtf8("menu_Verbrauch"))
        self.menu_Lagerstand = QtGui.QMenu(self.menu_Reports)
        self.menu_Lagerstand.setObjectName(_fromUtf8("menu_Lagerstand"))
        self.menu_Personal_2 = QtGui.QMenu(self.menu_Reports)
        self.menu_Personal_2.setObjectName(_fromUtf8("menu_Personal_2"))
        self.menu_Lieferungen = QtGui.QMenu(self.menubar)
        self.menu_Lieferungen.setObjectName(_fromUtf8("menu_Lieferungen"))
        self.menuStammdaten = QtGui.QMenu(self.menubar)
        self.menuStammdaten.setObjectName(_fromUtf8("menuStammdaten"))
        self.menu_Dokumente = QtGui.QMenu(self.menubar)
        self.menu_Dokumente.setObjectName(_fromUtf8("menu_Dokumente"))
        self.menu_Personal = QtGui.QMenu(self.menubar)
        self.menu_Personal.setObjectName(_fromUtf8("menu_Personal"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.action_Lieferungen_Lieferungen = QtGui.QAction(MainWindow)
        self.action_Lieferungen_Lieferungen.setObjectName(_fromUtf8("action_Lieferungen_Lieferungen"))
        self.action_Lieferungen_Lieferanten = QtGui.QAction(MainWindow)
        self.action_Lieferungen_Lieferanten.setObjectName(_fromUtf8("action_Lieferungen_Lieferanten"))
        self.actionZoomIn = QtGui.QAction(MainWindow)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoomOut = QtGui.QAction(MainWindow)
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.action_Report_Lager_Lagerstand = QtGui.QAction(MainWindow)
        self.action_Report_Lager_Lagerstand.setObjectName(_fromUtf8("action_Report_Lager_Lagerstand"))
        self.action_Report_Lager_MinimumLagerstand = QtGui.QAction(MainWindow)
        self.action_Report_Lager_MinimumLagerstand.setObjectName(_fromUtf8("action_Report_Lager_MinimumLagerstand"))
        self.action_Stammdaten_Perioden = QtGui.QAction(MainWindow)
        self.action_Stammdaten_Perioden.setObjectName(_fromUtf8("action_Stammdaten_Perioden"))
        self.action_Lieferungen_InitialerLagerstand = QtGui.QAction(MainWindow)
        self.action_Lieferungen_InitialerLagerstand.setObjectName(_fromUtf8("action_Lieferungen_InitialerLagerstand"))
        self.action_Report_Verbrauch_Artikel = QtGui.QAction(MainWindow)
        self.action_Report_Verbrauch_Artikel.setObjectName(_fromUtf8("action_Report_Verbrauch_Artikel"))
        self.actionAuf_wand = QtGui.QAction(MainWindow)
        self.actionAuf_wand.setObjectName(_fromUtf8("actionAuf_wand"))
        self.action_Report_Umsaetze_UmsatzTag = QtGui.QAction(MainWindow)
        self.action_Report_Umsaetze_UmsatzTag.setObjectName(_fromUtf8("action_Report_Umsaetze_UmsatzTag"))
        self.action_Report_Umsaetze_UmsatzAufwand = QtGui.QAction(MainWindow)
        self.action_Report_Umsaetze_UmsatzAufwand.setObjectName(_fromUtf8("action_Report_Umsaetze_UmsatzAufwand"))
        self.action_Report_Lager_Inventur = QtGui.QAction(MainWindow)
        self.action_Report_Lager_Inventur.setObjectName(_fromUtf8("action_Report_Lager_Inventur"))
        self.action_Stammdaten_Import = QtGui.QAction(MainWindow)
        self.action_Stammdaten_Import.setObjectName(_fromUtf8("action_Stammdaten_Import"))
        self.action_Report_Einkauf_GesamteLieferungen = QtGui.QAction(MainWindow)
        self.action_Report_Einkauf_GesamteLieferungen.setObjectName(_fromUtf8("action_Report_Einkauf_GesamteLieferungen"))
        self.action_Dokumente_Dokumenttypen = QtGui.QAction(MainWindow)
        self.action_Dokumente_Dokumenttypen.setObjectName(_fromUtf8("action_Dokumente_Dokumenttypen"))
        self.action_Dokumente_Dokumente = QtGui.QAction(MainWindow)
        self.action_Dokumente_Dokumente.setObjectName(_fromUtf8("action_Dokumente_Dokumente"))
        self.action_Stammdaten_Steuersaetze = QtGui.QAction(MainWindow)
        self.action_Stammdaten_Steuersaetze.setObjectName(_fromUtf8("action_Stammdaten_Steuersaetze"))
        self.action_Stammdaten_Liefereinheiten = QtGui.QAction(MainWindow)
        self.action_Stammdaten_Liefereinheiten.setObjectName(_fromUtf8("action_Stammdaten_Liefereinheiten"))
        self.action_Report_Umsaetze_AufwanddetailsProTag = QtGui.QAction(MainWindow)
        self.action_Report_Umsaetze_AufwanddetailsProTag.setObjectName(_fromUtf8("action_Report_Umsaetze_AufwanddetailsProTag"))
        self.action_Report_Umsaetze_DurchschUmsatzWochentag = QtGui.QAction(MainWindow)
        self.action_Report_Umsaetze_DurchschUmsatzWochentag.setObjectName(_fromUtf8("action_Report_Umsaetze_DurchschUmsatzWochentag"))
        self.action_Report_Einkauf_Verprobung = QtGui.QAction(MainWindow)
        self.action_Report_Einkauf_Verprobung.setObjectName(_fromUtf8("action_Report_Einkauf_Verprobung"))
        self.action_Personal_DienstplanErstellen = QtGui.QAction(MainWindow)
        self.action_Personal_DienstplanErstellen.setObjectName(_fromUtf8("action_Personal_DienstplanErstellen"))
        self.action_Personal_Dienstnehmer = QtGui.QAction(MainWindow)
        self.action_Personal_Dienstnehmer.setObjectName(_fromUtf8("action_Personal_Dienstnehmer"))
        self.action_Personal_Beschaeftigungsbereiche = QtGui.QAction(MainWindow)
        self.action_Personal_Beschaeftigungsbereiche.setObjectName(_fromUtf8("action_Personal_Beschaeftigungsbereiche"))
        self.action_Personal_Arbeitsplaetze = QtGui.QAction(MainWindow)
        self.action_Personal_Arbeitsplaetze.setObjectName(_fromUtf8("action_Personal_Arbeitsplaetze"))
        self.action_Stammdaten_Veranstaltungen = QtGui.QAction(MainWindow)
        self.action_Stammdaten_Veranstaltungen.setObjectName(_fromUtf8("action_Stammdaten_Veranstaltungen"))
        self.action_Report_Personal_DienstnehmerStunden = QtGui.QAction(MainWindow)
        self.action_Report_Personal_DienstnehmerStunden.setObjectName(_fromUtf8("action_Report_Personal_DienstnehmerStunden"))
        self.action_Stammdaten_Buchungskonten = QtGui.QAction(MainWindow)
        self.action_Stammdaten_Buchungskonten.setObjectName(_fromUtf8("action_Stammdaten_Buchungskonten"))
        self.action_Stammdaten_Konfiguration = QtGui.QAction(MainWindow)
        self.action_Stammdaten_Konfiguration.setObjectName(_fromUtf8("action_Stammdaten_Konfiguration"))
        self.action_Personal_DienstnehmerEreignisse = QtGui.QAction(MainWindow)
        self.action_Personal_DienstnehmerEreignisse.setObjectName(_fromUtf8("action_Personal_DienstnehmerEreignisse"))
        self.action_Stammdaten_DNEreignisTypen = QtGui.QAction(MainWindow)
        self.action_Stammdaten_DNEreignisTypen.setObjectName(_fromUtf8("action_Stammdaten_DNEreignisTypen"))
        self.action_Personal_Gehaelter = QtGui.QAction(MainWindow)
        self.action_Personal_Gehaelter.setObjectName(_fromUtf8("action_Personal_Gehaelter"))
        self.action_Personal_Loehne = QtGui.QAction(MainWindow)
        self.action_Personal_Loehne.setObjectName(_fromUtf8("action_Personal_Loehne"))
        self.menuFile.addAction(self.actionQuit)
        self.menu_Einkauf.addAction(self.action_Report_Einkauf_GesamteLieferungen)
        self.menu_Einkauf.addAction(self.action_Report_Einkauf_Verprobung)
        self.menu_Umsaetze.addAction(self.action_Report_Umsaetze_UmsatzTag)
        self.menu_Umsaetze.addAction(self.action_Report_Umsaetze_UmsatzAufwand)
        self.menu_Umsaetze.addAction(self.action_Report_Umsaetze_AufwanddetailsProTag)
        self.menu_Umsaetze.addAction(self.action_Report_Umsaetze_DurchschUmsatzWochentag)
        self.menu_Verbrauch.addAction(self.action_Report_Verbrauch_Artikel)
        self.menu_Lagerstand.addAction(self.action_Report_Lager_Lagerstand)
        self.menu_Lagerstand.addAction(self.action_Report_Lager_MinimumLagerstand)
        self.menu_Lagerstand.addAction(self.action_Report_Lager_Inventur)
        self.menu_Personal_2.addAction(self.action_Report_Personal_DienstnehmerStunden)
        self.menu_Reports.addAction(self.menu_Lagerstand.menuAction())
        self.menu_Reports.addAction(self.menu_Verbrauch.menuAction())
        self.menu_Reports.addAction(self.menu_Umsaetze.menuAction())
        self.menu_Reports.addAction(self.menu_Einkauf.menuAction())
        self.menu_Reports.addAction(self.menu_Personal_2.menuAction())
        self.menu_Lieferungen.addAction(self.action_Lieferungen_Lieferungen)
        self.menu_Lieferungen.addAction(self.action_Lieferungen_Lieferanten)
        self.menu_Lieferungen.addAction(self.action_Lieferungen_InitialerLagerstand)
        self.menuStammdaten.addAction(self.action_Stammdaten_Perioden)
        self.menuStammdaten.addAction(self.action_Stammdaten_Import)
        self.menuStammdaten.addAction(self.action_Stammdaten_Steuersaetze)
        self.menuStammdaten.addAction(self.action_Stammdaten_Liefereinheiten)
        self.menuStammdaten.addAction(self.action_Stammdaten_Veranstaltungen)
        self.menuStammdaten.addAction(self.action_Stammdaten_Buchungskonten)
        self.menuStammdaten.addAction(self.action_Stammdaten_DNEreignisTypen)
        self.menuStammdaten.addSeparator()
        self.menuStammdaten.addAction(self.action_Stammdaten_Konfiguration)
        self.menu_Dokumente.addAction(self.action_Dokumente_Dokumenttypen)
        self.menu_Dokumente.addAction(self.action_Dokumente_Dokumente)
        self.menu_Personal.addAction(self.action_Personal_DienstplanErstellen)
        self.menu_Personal.addAction(self.action_Personal_Dienstnehmer)
        self.menu_Personal.addAction(self.action_Personal_Beschaeftigungsbereiche)
        self.menu_Personal.addAction(self.action_Personal_Arbeitsplaetze)
        self.menu_Personal.addAction(self.action_Personal_DienstnehmerEreignisse)
        self.menu_Personal.addAction(self.action_Personal_Gehaelter)
        self.menu_Personal.addAction(self.action_Personal_Loehne)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Reports.menuAction())
        self.menubar.addAction(self.menu_Lieferungen.menuAction())
        self.menubar.addAction(self.menu_Dokumente.menuAction())
        self.menubar.addAction(self.menu_Personal.menuAction())
        self.menubar.addAction(self.menuStammdaten.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Reports.setTitle(QtGui.QApplication.translate("MainWindow", "&Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Einkauf.setTitle(QtGui.QApplication.translate("MainWindow", "&Einkauf", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Umsaetze.setTitle(QtGui.QApplication.translate("MainWindow", "&Umsätze", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Verbrauch.setTitle(QtGui.QApplication.translate("MainWindow", "&Verbrauch", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Lagerstand.setTitle(QtGui.QApplication.translate("MainWindow", "&Lager", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Personal_2.setTitle(QtGui.QApplication.translate("MainWindow", "&Personal", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Lieferungen.setTitle(QtGui.QApplication.translate("MainWindow", "&Lieferungen", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStammdaten.setTitle(QtGui.QApplication.translate("MainWindow", "&Stammdaten", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Dokumente.setTitle(QtGui.QApplication.translate("MainWindow", "Do&kumente", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Personal.setTitle(QtGui.QApplication.translate("MainWindow", "&Personal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Lieferungen_Lieferungen.setText(QtGui.QApplication.translate("MainWindow", "&Lieferungen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Lieferungen_Lieferanten.setText(QtGui.QApplication.translate("MainWindow", "L&ieferanten", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "&Vergrößern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setToolTip(QtGui.QApplication.translate("MainWindow", "Vergrößern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Verkleinern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setToolTip(QtGui.QApplication.translate("MainWindow", "Verkleinern", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Lager_Lagerstand.setText(QtGui.QApplication.translate("MainWindow", "&Lagerstand", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Lager_MinimumLagerstand.setText(QtGui.QApplication.translate("MainWindow", "&Minimum erreicht", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stammdaten_Perioden.setText(QtGui.QApplication.translate("MainWindow", "&Perioden", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Lieferungen_InitialerLagerstand.setText(QtGui.QApplication.translate("MainWindow", "Initialer Lager&stand", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Verbrauch_Artikel.setText(QtGui.QApplication.translate("MainWindow", "&Artikel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAuf_wand.setText(QtGui.QApplication.translate("MainWindow", "Auf&wand", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Umsaetze_UmsatzTag.setText(QtGui.QApplication.translate("MainWindow", "&Umsatz/Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Umsaetze_UmsatzAufwand.setText(QtGui.QApplication.translate("MainWindow", "Umsatz:&Aufwand", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Lager_Inventur.setText(QtGui.QApplication.translate("MainWindow", "&Inventur", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stammdaten_Import.setText(QtGui.QApplication.translate("MainWindow", "&Import", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Einkauf_GesamteLieferungen.setText(QtGui.QApplication.translate("MainWindow", "&Gesamte Lieferungen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Dokumente_Dokumenttypen.setText(QtGui.QApplication.translate("MainWindow", "Dokument&typen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Dokumente_Dokumente.setText(QtGui.QApplication.translate("MainWindow", "&Dokumente", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stammdaten_Steuersaetze.setText(QtGui.QApplication.translate("MainWindow", "&Steuersätze", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stammdaten_Liefereinheiten.setText(QtGui.QApplication.translate("MainWindow", "&Liefereinheiten", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Umsaetze_AufwanddetailsProTag.setText(QtGui.QApplication.translate("MainWindow", "Aufwanddetails/&Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Umsaetze_DurchschUmsatzWochentag.setText(QtGui.QApplication.translate("MainWindow", "&Durchsch. Umsatz/Wochentag", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Einkauf_Verprobung.setText(QtGui.QApplication.translate("MainWindow", "&Verprobung", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Personal_DienstplanErstellen.setText(QtGui.QApplication.translate("MainWindow", "Dienstplan &erstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Personal_Dienstnehmer.setText(QtGui.QApplication.translate("MainWindow", "&Dienstnehmer", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Personal_Beschaeftigungsbereiche.setText(QtGui.QApplication.translate("MainWindow", "&Beschäftigungsbereiche", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Personal_Arbeitsplaetze.setText(QtGui.QApplication.translate("MainWindow", "&Arbeitsplätze", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stammdaten_Veranstaltungen.setText(QtGui.QApplication.translate("MainWindow", "&Veranstaltungen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Report_Personal_DienstnehmerStunden.setText(QtGui.QApplication.translate("MainWindow", "Dienstnehmer &Stunden", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stammdaten_Buchungskonten.setText(QtGui.QApplication.translate("MainWindow", "&Buchungskonten", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stammdaten_Konfiguration.setText(QtGui.QApplication.translate("MainWindow", "&Konfiguration", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Personal_DienstnehmerEreignisse.setText(QtGui.QApplication.translate("MainWindow", "E&reignisse", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stammdaten_DNEreignisTypen.setText(QtGui.QApplication.translate("MainWindow", "DN Ereignis &Typen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Personal_Gehaelter.setText(QtGui.QApplication.translate("MainWindow", "&Gehälter", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Personal_Loehne.setText(QtGui.QApplication.translate("MainWindow", "&Löhne", None, QtGui.QApplication.UnicodeUTF8))

