# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/statsMainWindow.ui'
#
# Created: Thu Aug  2 22:49:52 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_start = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_start.sizePolicy().hasHeightForWidth())
        self.comboBox_start.setSizePolicy(sizePolicy)
        self.comboBox_start.setObjectName("comboBox_start")
        self.horizontalLayout.addWidget(self.comboBox_start)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_end = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_end.sizePolicy().hasHeightForWidth())
        self.comboBox_end.setSizePolicy(sizePolicy)
        self.comboBox_end.setObjectName("comboBox_end")
        self.horizontalLayout.addWidget(self.comboBox_end)
        self.pushButton_start = QtGui.QPushButton(self.frame)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        self.pushButton_zoomIn = QtGui.QPushButton(self.frame)
        self.pushButton_zoomIn.setAutoRepeat(True)
        self.pushButton_zoomIn.setObjectName("pushButton_zoomIn")
        self.horizontalLayout.addWidget(self.pushButton_zoomIn)
        self.pushButton_zoomOut = QtGui.QPushButton(self.frame)
        self.pushButton_zoomOut.setAutoRepeat(True)
        self.pushButton_zoomOut.setObjectName("pushButton_zoomOut")
        self.horizontalLayout.addWidget(self.pushButton_zoomOut)
        self.checkBox_showTotal = QtGui.QCheckBox(self.frame)
        self.checkBox_showTotal.setObjectName("checkBox_showTotal")
        self.horizontalLayout.addWidget(self.checkBox_showTotal)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_articles = QtGui.QPushButton(self.frame)
        self.pushButton_articles.setObjectName("pushButton_articles")
        self.horizontalLayout.addWidget(self.pushButton_articles)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_syncDB = QtGui.QPushButton(self.frame)
        self.pushButton_syncDB.setObjectName("pushButton_syncDB")
        self.horizontalLayout_9.addWidget(self.pushButton_syncDB)
        self.pushButton_importArticles = QtGui.QPushButton(self.frame)
        self.pushButton_importArticles.setObjectName("pushButton_importArticles")
        self.horizontalLayout_9.addWidget(self.pushButton_importArticles)
        self.comboBox = QtGui.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_9.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_revenues = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_revenues.setChecked(True)
        self.radioButton_revenues.setObjectName("radioButton_revenues")
        self.horizontalLayout_4.addWidget(self.radioButton_revenues)
        self.radioButton_quantity = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_quantity.setObjectName("radioButton_quantity")
        self.horizontalLayout_4.addWidget(self.radioButton_quantity)
        self.radioButton_consumption = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_consumption.setObjectName("radioButton_consumption")
        self.horizontalLayout_4.addWidget(self.radioButton_consumption)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_lineChart = QtGui.QRadioButton(self.groupBox)
        self.radioButton_lineChart.setChecked(True)
        self.radioButton_lineChart.setObjectName("radioButton_lineChart")
        self.horizontalLayout_3.addWidget(self.radioButton_lineChart)
        self.radioButton_barChart = QtGui.QRadioButton(self.groupBox)
        self.radioButton_barChart.setObjectName("radioButton_barChart")
        self.horizontalLayout_3.addWidget(self.radioButton_barChart)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_personalUse = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_personalUse.setObjectName("checkBox_personalUse")
        self.horizontalLayout_8.addWidget(self.checkBox_personalUse)
        self.checkBox_onlyNegative = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_onlyNegative.setObjectName("checkBox_onlyNegative")
        self.horizontalLayout_8.addWidget(self.checkBox_onlyNegative)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_weekday0 = QtGui.QCheckBox(self.frame)
        self.checkBox_weekday0.setObjectName("checkBox_weekday0")
        self.horizontalLayout_5.addWidget(self.checkBox_weekday0)
        self.checkBox_weekday1 = QtGui.QCheckBox(self.frame)
        self.checkBox_weekday1.setObjectName("checkBox_weekday1")
        self.horizontalLayout_5.addWidget(self.checkBox_weekday1)
        self.checkBox_weekday2 = QtGui.QCheckBox(self.frame)
        self.checkBox_weekday2.setObjectName("checkBox_weekday2")
        self.horizontalLayout_5.addWidget(self.checkBox_weekday2)
        self.checkBox_weekday3 = QtGui.QCheckBox(self.frame)
        self.checkBox_weekday3.setObjectName("checkBox_weekday3")
        self.horizontalLayout_5.addWidget(self.checkBox_weekday3)
        self.checkBox_weekday4 = QtGui.QCheckBox(self.frame)
        self.checkBox_weekday4.setObjectName("checkBox_weekday4")
        self.horizontalLayout_5.addWidget(self.checkBox_weekday4)
        self.checkBox_weekday5 = QtGui.QCheckBox(self.frame)
        self.checkBox_weekday5.setObjectName("checkBox_weekday5")
        self.horizontalLayout_5.addWidget(self.checkBox_weekday5)
        self.checkBox_weekday6 = QtGui.QCheckBox(self.frame)
        self.checkBox_weekday6.setObjectName("checkBox_weekday6")
        self.horizontalLayout_5.addWidget(self.checkBox_weekday6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pushButton_export = QtGui.QPushButton(self.frame)
        self.pushButton_export.setObjectName("pushButton_export")
        self.horizontalLayout_5.addWidget(self.pushButton_export)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.graphicsView_stats = StatsGraphicsView(self.centralwidget)
        self.graphicsView_stats.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.graphicsView_stats.setObjectName("graphicsView_stats")
        self.gridLayout_2.addWidget(self.graphicsView_stats, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.comboBox_start)
        self.label_2.setBuddy(self.comboBox_end)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_start, self.comboBox_end)
        MainWindow.setTabOrder(self.comboBox_end, self.pushButton_start)
        MainWindow.setTabOrder(self.pushButton_start, self.checkBox_weekday0)
        MainWindow.setTabOrder(self.checkBox_weekday0, self.checkBox_weekday1)
        MainWindow.setTabOrder(self.checkBox_weekday1, self.checkBox_weekday2)
        MainWindow.setTabOrder(self.checkBox_weekday2, self.checkBox_weekday3)
        MainWindow.setTabOrder(self.checkBox_weekday3, self.checkBox_weekday4)
        MainWindow.setTabOrder(self.checkBox_weekday4, self.checkBox_weekday5)
        MainWindow.setTabOrder(self.checkBox_weekday5, self.checkBox_weekday6)
        MainWindow.setTabOrder(self.checkBox_weekday6, self.pushButton_zoomIn)
        MainWindow.setTabOrder(self.pushButton_zoomIn, self.pushButton_zoomOut)
        MainWindow.setTabOrder(self.pushButton_zoomOut, self.pushButton_articles)
        MainWindow.setTabOrder(self.pushButton_articles, self.graphicsView_stats)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Fr&om", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "T&ill", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_start.setText(QtGui.QApplication.translate("MainWindow", "&Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_zoomIn.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_zoomOut.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_showTotal.setText(QtGui.QApplication.translate("MainWindow", "Sh&ow Total", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_articles.setText(QtGui.QApplication.translate("MainWindow", "&Articles", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_syncDB.setText(QtGui.QApplication.translate("MainWindow", "&Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_importArticles.setText(QtGui.QApplication.translate("MainWindow", "&Import Articles", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "What", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_revenues.setText(QtGui.QApplication.translate("MainWindow", "&Revenues", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_quantity.setText(QtGui.QApplication.translate("MainWindow", "&Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_consumption.setText(QtGui.QApplication.translate("MainWindow", "&Consumption", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Chart Type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_lineChart.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_barChart.setText(QtGui.QApplication.translate("MainWindow", "Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_personalUse.setText(QtGui.QApplication.translate("MainWindow", "Personal Use", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_onlyNegative.setText(QtGui.QApplication.translate("MainWindow", "Only Negative", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_weekday0.setText(QtGui.QApplication.translate("MainWindow", "&Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_weekday1.setText(QtGui.QApplication.translate("MainWindow", "&Tuesday", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_weekday2.setText(QtGui.QApplication.translate("MainWindow", "&Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_weekday3.setText(QtGui.QApplication.translate("MainWindow", "T&hursday", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_weekday4.setText(QtGui.QApplication.translate("MainWindow", "&Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_weekday5.setText(QtGui.QApplication.translate("MainWindow", "&Saturday", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_weekday6.setText(QtGui.QApplication.translate("MainWindow", "S&unday", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export.setText(QtGui.QApplication.translate("MainWindow", "&Export", None, QtGui.QApplication.UnicodeUTF8))

from StatsGraphicsView import StatsGraphicsView
